# -*- coding: utf-8 -*-
"""DSP_310_Midterm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UVV7avULiqvcsK2amEof37Du1aR3sDMH

Riva Poudel

DSP 310

Midterm 

Due: 03.29.2021
"""

# preamble to be able to run notebooks in Colab
from google.colab import drive
import sys

# mount the drive
drive.mount('/content/drive') 

# useful folders
notes_home = "/content/drive/Shared drives/CSC310/ds/notes/"
user_home = "/content/drive/My Drive/"
    
# insert the notes folder into the path so we can include assets modules etc
sys.path.insert(1,notes_home)

import pandas as pd
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from assets.confint import classification_confint

# get data
df = pd.read_csv("/content/drive/Shared drives/CSC310/credit_predict.csv")
df.head(n=5)

#New Data Set Without Gender Value and Rating_Label Columns
df_new = df.drop(['Gender_Val','Rating_Label'], axis=1)
df_new.describe()

"""## **PART II:**

1. There are 7 independent variables in this data set.

2. Descriptive Statistics
  - Income 
    - Min: 10.35
    - Max: 186.63
    - Mean: 45.21
  - Limit
    - Min: 855
    - Max: 13913
    - Mean: 4735.6
  - Cards
    - Min: 1
    - Max: 9
    - Mean: 3
  - Age
    - Min: 23
    - Max: 98
    - Mean: 55.6
  - Education
    - Min: 5
    - Max: 20
    - Mean: 13.45
  - Gender Value
    - Inconclusive, the numbers represent the the gender of the individual in the data set.
  - Rating Label
    - Inconclusive, the data is a description and cannot be computed.

3. Determining whether the variables are Multi-Modal
"""

# Histogram of Income
df_new['Income'].hist()

"""Income is a **Unimodal** because the data is clustered together at one point. """

#Histogram of Limit
df_new['Limit'].hist()

"""Limit is also **Unimodal** because the data is clustered at one point"""

#Histogram of Cards
df_new['Cards'].hist()

"""Cards are **Bimodal** because there are points on the historgram that the data peaks at. """

#Histogram of Age
df_new['Age'].hist()

"""Age is clearly **Uniform** because it remains roughly the same throughout the graph. """

#Histogram of Education
df_new['Education'].hist()

"""Education is **Mulitmodal** because there are multiple 'peaks' or clusters of data at multiple points. """

#Scatter Plot of all Variables
scatter_plot = pd.plotting.scatter_matrix(df_new, figsize=[15,15])

"""4. Income and Limit have a strong positive correlation. The scatter plot shows that the higher the income of the individual in the data file, the higher their limit is set. What is additionally interesting about the data set, is that Income and Limit are the only two variables that have a correlation. The following two scatter plots, Age and Education, and Limit and Cards, are an example of other correlations between the variables (or lack thereof). The majority of the variables have no clear pattern or relation. In comparison, the scatter plot of Limit and Income have a cluster at the bottom of the graph. The conclusion is that the higher the income of the indiviual, the higher the limit is set. The data is clustered at the bottom of the graph, because the majority of the individuals have a lower income, thus a lower limit. """

print('Income and Limit Scatter Plot')
df_new.plot.scatter(x='Limit', y= 'Income')

"""5. There are 3 units that are computable in the dependent variable. The number of years, amount of money, and number of cards. There are two additional dependent variables that are not computable. (0,1) is meant to signify gender, and (fair, poorly) which is the rating of the individuals credit. 
6. The data set is balenced. This is because the individual variables in the data set satisfy the order of ten and the minimum's and maximum's are around the same magnitude. 
"""